// <auto-generated />
namespace EasyPlan.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class SetEmailAsId : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SetEmailAsId));
        
        string IMigrationMetadata.Id
        {
            get { return "201607221411047_SetEmailAsId"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
